### ISSUE TITLE
Can not running start.app

### ISSUE THREAD

**Issue by Brunosilva84** [hugeinc/styleguide#100]
Guys sorry, how should I do with this error?
Thanks.

Styleguide. Welcome!
PROGRESS:0
PROGRESS:50

Checking dependencies...

/private/var/folders/l5/ykrry02j0cg0t3fyv4gxg6kh0000gn/T/AppTranslocation/9565D205-1016-4FDD-9BB4-BD23A627328F/d/Start.app/Contents/Resources/script: line 31: cd: ../../../styleguide/structure/_node-files: No such file or directory
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/l5/ykrry02j0cg0t3fyv4gxg6kh0000gn/T/AppTranslocation/9565D205-1016-4FDD-9BB4-BD23A627328F/d/Start.app/Contents/Resources/package.json'
npm WARN Resources No description
npm WARN Resources No repository field.
npm WARN Resources No README data
npm WARN Resources No license field.
npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/brunosilva/local/bin/node" "/Users/brunosilva/local/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v4.1.1
npm ERR! path /private/var/folders/l5/ykrry02j0cg0t3fyv4gxg6kh0000gn/T/AppTranslocation/9565D205-1016-4FDD-9BB4-BD23A627328F/d/Start.app/Contents/Resources/node_modules/.staging
npm ERR! code EROFS
npm ERR! errno -30
npm ERR! syscall mkdir

npm ERR! rofs EROFS: read-only file system, mkdir '/private/var/folders/l5/ykrry02j0cg0t3fyv4gxg6kh0000gn/T/AppTranslocation/9565D205-1016-4FDD-9BB4-BD23A627328F/d/Start.app/Contents/Resources/node_modules/.staging'
npm ERR! rofs This is most likely not a problem with npm itself
npm ERR! rofs and is related to the file system being read-only.
npm ERR! rofs 
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.
npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/brunosilva/local/bin/node" "/Users/brunosilva/local/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v4.1.1
npm ERR! path npm-debug.log.3088471304
npm ERR! code EROFS
npm ERR! errno -30
npm ERR! syscall open

npm ERR! rofs EROFS: read-only file system, open 'npm-debug.log.3088471304'
npm ERR! rofs This is most likely not a problem with npm itself
npm ERR! rofs and is related to the file system being read-only.
npm ERR! rofs 
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/l5/ykrry02j0cg0t3fyv4gxg6kh0000gn/T/AppTranslocation/9565D205-1016-4FDD-9BB4-BD23A627328F/d/Start.app/Contents/Resources/npm-debug.log
PROGRESS:80
touch: .install.lock: Read-only file system
/private/var/folders/l5/ykrry02j0cg0t3fyv4gxg6kh0000gn/T/AppTranslocation/9565D205-1016-4FDD-9BB4-BD23A627328F/d/Start.app/Contents/Resources/script: line 35: cd: styleguide/structure/_node-files: No such file or directory

Let's start this thing...
module.js:442
    throw err;
    ^

Error: Cannot find module '/private/var/folders/l5/ykrry02j0cg0t3fyv4gxg6kh0000gn/T/AppTranslocation/9565D205-1016-4FDD-9BB4-BD23A627328F/d/watch.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3
PROGRESS:100

**Comment by ideacco** [comment]
I have also encountered the same problem

**Comment by charlottechen1993** [comment]
Experienced the same issue :(

**Comment by caiovaccaro** [comment]
Updating the dependencies version solved for me. Just pushed to a separate branch. If you can please test, downloading a zip from this link: https://github.com/hugeinc/styleguide/tree/hotfix/dependencies-version

**Comment by charlottechen1993** [comment]
Actually I just downloaded the windows/linux package and did manual installation and it worked. Thanks for the update.

**Comment by dlewand691** [comment]
Just tried the dependencies version with no luck. Still getting the same errors.
