### ISSUE TITLE
Cannot run start file

### ISSUE THREAD

**Issue by Arno3N** [hugeinc/styleguide#102]
Here is the full install log:

Styleguide. Welcome!
PROGRESS:0
PROGRESS:50

Checking dependencies...

/private/var/folders/yj/qs8g4y955k92s53bdclx019w0000gn/T/AppTranslocation/04A4A291-E77A-45ED-A3C6-558A643CB5FF/d/Start.app/Contents/Resources/script: line 31: cd: ../../../styleguide/structure/_node-files: No such file or directory
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/yj/qs8g4y955k92s53bdclx019w0000gn/T/AppTranslocation/04A4A291-E77A-45ED-A3C6-558A643CB5FF/d/Start.app/Contents/Resources/package.json'
npm WARN Resources No description
npm WARN Resources No repository field.
npm WARN Resources No README data
npm WARN Resources No license field.
npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/Arno/.nvm/versions/node/v5.7.1/bin/node" "/Users/Arno/.nvm/versions/node/v5.7.1/bin/npm" "install"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! path /private/var/folders/yj/qs8g4y955k92s53bdclx019w0000gn/T/AppTranslocation/04A4A291-E77A-45ED-A3C6-558A643CB5FF/d/Start.app/Contents/Resources/node_modules/.staging
npm ERR! code EROFS
npm ERR! errno -30
npm ERR! syscall mkdir

npm ERR! rofs EROFS: read-only file system, mkdir '/private/var/folders/yj/qs8g4y955k92s53bdclx019w0000gn/T/AppTranslocation/04A4A291-E77A-45ED-A3C6-558A643CB5FF/d/Start.app/Contents/Resources/node_modules/.staging'
npm ERR! rofs This is most likely not a problem with npm itself
npm ERR! rofs and is related to the file system being read-only.
npm ERR! rofs 
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.
npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/Arno/.nvm/versions/node/v5.7.1/bin/node" "/Users/Arno/.nvm/versions/node/v5.7.1/bin/npm" "install"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! path npm-debug.log.1033846692
npm ERR! code EROFS
npm ERR! errno -30
npm ERR! syscall open

npm ERR! rofs EROFS: read-only file system, open 'npm-debug.log.1033846692'
npm ERR! rofs This is most likely not a problem with npm itself
npm ERR! rofs and is related to the file system being read-only.
npm ERR! rofs 
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/yj/qs8g4y955k92s53bdclx019w0000gn/T/AppTranslocation/04A4A291-E77A-45ED-A3C6-558A643CB5FF/d/Start.app/Contents/Resources/npm-debug.log
PROGRESS:80
touch: .install.lock: Read-only file system
/private/var/folders/yj/qs8g4y955k92s53bdclx019w0000gn/T/AppTranslocation/04A4A291-E77A-45ED-A3C6-558A643CB5FF/d/Start.app/Contents/Resources/script: line 35: cd: styleguide/structure/_node-files: No such file or directory

Let's start this thing...
module.js:341
    throw err;
    ^

Error: Cannot find module '/private/var/folders/yj/qs8g4y955k92s53bdclx019w0000gn/T/AppTranslocation/04A4A291-E77A-45ED-A3C6-558A643CB5FF/d/watch.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
PROGRESS:100

**Comment by septk** [comment]
same here

**Comment by BecLai** [comment]
Same here, help please!
