### ISSUE TITLE
Cannot Start

### ISSUE THREAD

**Issue by estoria** [hugeinc/styleguide#103]
I'm having this error

`Styleguide. Welcome!
PROGRESS:0
PROGRESS:50

Checking dependencies...

/Users/jingxin/.rvm/scripts/extras/bash_zsh_support/chpwd/function.sh: line 5: cd: ../../../styleguide/structure/_node-files: No such file or directory
/private/var/folders/1l/4x345n8d2z99ds0w3dt3_mkr0000gn/T/AppTranslocation/1F804C39-ADF6-43F4-8AA6-7372397B8D19/d/Start.app/Contents/Resources/script: line 32: npm: command not found
PROGRESS:80
touch: .install.lock: Read-only file system
/Users/jingxin/.rvm/scripts/extras/bash_zsh_support/chpwd/function.sh: line 5: cd: styleguide/structure/_node-files: No such file or directory

Let's start this thing...
module.js:442
    throw err;
    ^

Error: Cannot find module '/private/var/folders/1l/4x345n8d2z99ds0w3dt3_mkr0000gn/T/AppTranslocation/1F804C39-ADF6-43F4-8AA6-7372397B8D19/d/watch.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3
PROGRESS:100`

**Comment by AdamGerthel** [comment]
Same here, and I see this issue is pretty old. Not maintained anymore?

**Comment by iamshipon1988** [comment]
Try starting it manually. http://hugeinc.github.io/styleguide/start.html#manual-install

For me I'm getting errors 
```gyp ERR! cwd /Documents/Development/styleguide/structure/_node-files/node_modules/node-sass
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok ```
