### ISSUE TITLE
Deploying on AWS

### ISSUE THREAD

**Issue by cbaci** [hugeinc/styleguide#105]
So I'd like to deploy this on my AWS EC2 instance. I'm running on Amazon Linux AMI. I've deployed and installed everything via npm. I'd like to bypass the Harp server and use my own, already functioning Apache.

`[ec2-user@ip-XXX-XX-XX-XXX styleguide]$ cd /structure/_node-files && node watch.js
-bash: cd: /structure/_node-files: No such file or directory
[ec2-user@ip-XXX-XX-XX-XXX styleguide]$ cd styleguide/structure/_node-files && node watch.js
Starting Server on port 8000..
PROGRESS:94

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES, permission denied '/var/www/html/styleguide/styleguide/structure/_node-files/modules/../../../../styleguide/_data.json'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.writeFileSync (fs.js:978:15)
    at module.exports (/var/www/html/styleguide/styleguide/structure/_node-files/modules/write-date.js:34:8)
    at Object.module.exports.start (/var/www/html/styleguide/styleguide/structure/_node-files/modules/watcher.js:16:5)
    at ClientRequest.http.get.on.waitingTheServer (/var/www/html/styleguide/styleguide/structure/_node-files/watch.js:49:25)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1751:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:152:23)
    at Socket.socketOnData [as ondata] (http.js:1646:20)`

I guess I'm not sure I want to own port 8000 on a server that's already serving other stuff. Is there a best practice for deploying non-locally?

**Comment by caiovaccaro** [comment]
Hi, you need to run the compilation and serve just static HTML files ;)

**Comment by cbaci** [comment]
yep, I finally figured that out. Is Xcode req'd for generating the html files?

**Comment by caiovaccaro** [comment]
Not really but on a Mac it might need XCode Dev Tools in order to do some
things.
