### ISSUE TITLE
Unable to start on macOS Catalina beta 9

### ISSUE THREAD

**Issue by binc0** [hugeinc/styleguide#114]
Hello, I'm unable to start program I get this error now:
Error: Cannot find module '/private/var/folders/by/6v7jq9ps3lg0382sy5q52pvr0000gn/T/AppTranslocation/25DD1869-8B33-4190-AA8D-5B274BD52789/d/watch.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
PROGRESS:100

Before I got unable to check app integrity please contact the developer

**Comment by emersonk** [comment]
I'm having this same issue too. I tried the manual install as well, to no avail. I believe it's failing when trying to install harp. I tried to install harp manually and I didn't think it worked. After I attempted to install harp I tried running the Compile app and it failed immediately saying it couldn't find harp.

It appears others are having issues installing harp with npm: https://github.com/sintaxi/harp/issues/644
