### ISSUE TITLE
Mac Installer getting stuck at 94% but not solved by #34

### ISSUE THREAD

**Issue by catherine-jones** [hugeinc/styleguide#75]
Hi I am trying to install using the Mac installer, it looks like it is getting stuck so i looked at issue https://github.com/hugeinc/styleguide/issues/34. I followed the instructions but its still not working. I am using the latest version of OSX and XCode. Do you have any ideas what might be going wrong. I have tried the manual install and am still getting the same error

```
Error: listen EADDRINUSE :::8374
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at Server.listen (/Users/BitGirl/development/styleguide-master 2/styleguide/structure/_node-files/node_modules/livereload/lib/livereload.js:70:28)
    at Object.exports.createServer (/Users/BitGirl/development/styleguide-master 2/styleguide/structure/_node-files/node_modules/livereload/lib/livereload.js:216:12)
    at Object.module.exports.start (/Users/BitGirl/development/styleguide-master 2/styleguide/structure/_node-files/modules/livereloader.js:12:25)
    at Object.<anonymous> (/Users/BitGirl/development/styleguide-master 2/styleguide/structure/_node-files/watch.js:39:14)
    at Module._compile (module.js:434:26)```

**Comment by catherine-jones** [comment]
I believe this this may be related to the closed bug #47 which i noticed references Browser Sync, i do have this installed but it should not be running as I have done a system restart. I have also tried changing the port but this has not helped.

I am running OSX 10.11.3 on Mac

**Comment by GraphicDesk** [comment]
Make sure that you have Harp installed...

**Comment by caiovaccaro** [comment]
Hi @catherine-jones !

It seems to be a problem with the Livereload port, in this file: https://github.com/hugeinc/styleguide/blob/master/styleguide/structure/_node-files/modules/livereloader.js#L13

We can provide a patch that fixes that. If you want you can modify the file yourself, changing the port and seeing if it solves the problem.

**Comment by barnanorbert** [comment]
Hy, i have got the same problem like catherine's. I am using the latest version of OSX, with google chrome. The installer getting stuck at 94%. When im using the mac installer, getting this error.
<img width="931" alt="screen shot 2016-05-30 at 15 59 02" src="https://cloud.githubusercontent.com/assets/10828433/15654357/c210767e-2693-11e6-836a-b8aa21bbeab7.png">

but when im trying to install it manually
![harp](https://cloud.githubusercontent.com/assets/10828433/15654371/ec00fef4-2693-11e6-97d2-08a4128ace4b.png)

what should i do to make it work? 
Thanks!

**Comment by caiovaccaro** [comment]
Hi!

Can you please remove all the files, download and try again? I just updated all dependencies, Node version and fixed some bugs.

If you have NodeJS installed please make sure it is the latest version.

Thank you.

**Comment by barnanorbert** [comment]
After your hotfix, works like charm! Thank you mate!

**Comment by caiovaccaro** [comment]
Awesome!
