### ISSUE TITLE
Mac 10.11.3 - Error msg "Cannot find module 'websocket.io' "

### ISSUE THREAD

**Issue by appfobia** [hugeinc/styleguide#80]
<p>On running the "start.app" file I am getting the following error 
at Function.Module._load(module.js:300:12)</p>

<pre>
Error: Cannot find module 'websocket.io'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/soham/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/livereload/lib/livereload.js:9:8)
    at Object.<anonymous> (/Users/soham/Downloads/styleguide-master/styleguide/structure/_node-files/node_modules/livereload/lib/livereload.js:220:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
PROGRESS:100
</pre>

<p>I have no idea how to fix this.</p>

**Comment by caiovaccaro** [comment]
Hi!

Can you please remove all the files, download and try again? I just updated all dependencies, Node version and fixed some bugs.

If you have NodeJS installed please make sure it is the latest version.

Thank you.
