### ISSUE TITLE
Stucking at Progress: 94

### ISSUE THREAD

**Issue by programiro** [hugeinc/styleguide#93]
**After '$ node watch.js' im stucking on PROGRESS: 94**

LOG:

`
Starting Server on port 8000..
  PROGRESS:94

events.js:125
throw er; // Unhandled 'error' event
^
Error: watch ENFILE
at exports._errnoException (util.js:734:11)
at FSWatcher.start (fs.js:1216:11)
at Object.fs.watch (fs.js:1242:11)
at createFsWatchInstance (/Users/programiro/Sites/website-relaunch-2016/styleguide/structure/_node-files/node_modules/chokidar/lib/nodefs-handler.js:37:15)
at setFsWatchListener (/Users/programiro/Sites/website-relaunch-2016/styleguide/structure/_node-files/node_modules/chokidar/lib/nodefs-handler.js:80:15)
at FSWatcher.NodeFsHandler._watchWithNodeFs (/Users/programiro/Sites/website-relaunch-2016/styleguide/structure/_node-files/node_modules/chokidar/lib/nodefs-handler.js:228:14)
at FSWatcher.NodeFsHandler._handleFile (/Users/programiro/Sites/website-relaunch-2016/styleguide/structure/_node-files/node_modules/chokidar/lib/nodefs-handler.js:255:21)
at FSWatcher.<anonymous> (/Users/programiro/Sites/website-relaunch-2016/styleguide/structure/_node-files/node_modules/chokidar/lib/nodefs-handler.js:473:21)
at FSReqWrap.oncomplete (fs.js:73:15)
`

**Comment by programiro** [comment]
Had to install latest Harp:
$ sudo npm install -g harp@next


https://github.com/sintaxi/harp/issues/564

**Comment by caiovaccaro** [comment]
Thank you for the reference @programiro !
