### ISSUE TITLE
Cannot get style guide to start

### ISSUE THREAD

**Issue by mljoannou** [hugeinc/styleguide#94]
Please could you assist me? 

I have used brew to install node and npm, but cannot get it to run successfully ?

Error: Cannot find module 'watch'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/marcusjoannou/styleguide-master/styleguide/structure/_node-files/modules/watcher.js:6:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
PROGRESS:100

**Comment by caiovaccaro** [comment]
Hi @mljoannou , sorry for the late response. Have you tried manual installation? http://hugeinc.github.io/styleguide/start.html

**Comment by caiovaccaro** [comment]
Updating the dependencies version solved for me. Just pushed to a separate branch. If you can please test, downloading a zip from this link: https://github.com/hugeinc/styleguide/tree/hotfix/dependencies-version
