### ISSUE TITLE
Cannot run start file

### ISSUE THREAD

**Issue by rgustke** [hugeinc/styleguide#99]
Here is the error I'm getting

Styleguide. Welcome!
PROGRESS:0
PROGRESS:50

Checking dependencies...

/private/var/folders/n0/3l1q9541505dmglhf5d4w_k80000gp/T/AppTranslocation/CB0809F9-D715-43A9-BB9E-029982BBC388/d/Start.app/Contents/Resources/script: line 31: cd: ../../../styleguide/structure/_node-files: No such file or directory
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/n0/3l1q9541505dmglhf5d4w_k80000gp/T/AppTranslocation/CB0809F9-D715-43A9-BB9E-029982BBC388/d/Start.app/Contents/Resources/package.json'
npm WARN Resources No description
npm WARN Resources No repository field.
npm WARN Resources No README data
npm WARN Resources No license field.
npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/rgustke/local/bin/node" "/Users/rgustke/local/bin/npm" "install"
npm ERR! node v6.2.0
npm ERR! npm  v4.2.0
npm ERR! path /private/var/folders/n0/3l1q9541505dmglhf5d4w_k80000gp/T/AppTranslocation/CB0809F9-D715-43A9-BB9E-029982BBC388/d/Start.app/Contents/Resources/node_modules/.staging
npm ERR! code EROFS
npm ERR! errno -30
npm ERR! syscall mkdir

npm ERR! rofs EROFS: read-only file system, mkdir '/private/var/folders/n0/3l1q9541505dmglhf5d4w_k80000gp/T/AppTranslocation/CB0809F9-D715-43A9-BB9E-029982BBC388/d/Start.app/Contents/Resources/node_modules/.staging'
npm ERR! rofs This is most likely not a problem with npm itself
npm ERR! rofs and is related to the file system being read-only.
npm ERR! rofs 
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rgustke/.npm/_logs/2017-02-21T13_35_49_579Z-debug.log
PROGRESS:80
touch: .install.lock: Read-only file system
/private/var/folders/n0/3l1q9541505dmglhf5d4w_k80000gp/T/AppTranslocation/CB0809F9-D715-43A9-BB9E-029982BBC388/d/Start.app/Contents/Resources/script: line 35: cd: styleguide/structure/_node-files: No such file or directory

Let's start this thing...
module.js:442
    throw err;
    ^

Error: Cannot find module '/private/var/folders/n0/3l1q9541505dmglhf5d4w_k80000gp/T/AppTranslocation/CB0809F9-D715-43A9-BB9E-029982BBC388/d/watch.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3
PROGRESS:100

**Comment by caiovaccaro** [comment]
Hi there,

What is your operating system?

**Comment by rgustke** [comment]
I'm on Sierra 10.2.3 currently. Looks like this isn't compatible with 64bit OS... is there any way around this?

**Comment by caiovaccaro** [comment]
What is your Node version?

Updating the dependencies version solved for me. Just pushed to a separate branch. If you can please test, downloading a zip from this link: https://github.com/hugeinc/styleguide/tree/hotfix/dependencies-version

**Comment by kylanhurt** [comment]
@caiovaccaro I'm on node v.7.7.1 and I got the following issue:
```
ReferenceError: commandExists is not defined
    at Object.<anonymous> (/Users/kylanhurt/Documents/styleguide/styleguide/structure/_node-files/watch.js:26:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
PROGRESS:100
```
Unfortunately once it gets to "PROGRESS:100" I am not seeing anything happen.

**Comment by victorwhy** [comment]
@caiovaccaro I'm having the same issue as kylanhurt! i went onto your hotfix branch and now i'm getting the same error @kylanhurt is getting:

what node version do we need to be running? our designers would love to check this out, but it doesn't seem like the installs work.

```
$ cd styleguide/structure/_node-files && node watch.js
/styleguide-hotfix-dependencies-version/styleguide/structure/_node-files/watch.js:26
commandExists('harp', function(err, commandExists) {
^

ReferenceError: commandExists is not defined
    at Object.<anonymous> (/Users/victoryang/Projects/styleguide-hotfix-dependencies-version/styleguide/structure/_node-files/watch.js:26:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**Comment by victorwhy** [comment]
and using the start app it's not much better :T

```
(B[m/Users/victoryang/.extra: line 32: heroku-prod-deployed-commit=!sh: command not found
/Users/victoryang/.extra: line 33: compare-heroku=!sh: command not found
(B[m/Users/victoryang/.extra: line 32: heroku-prod-deployed-commit=!sh: command not found
/Users/victoryang/.extra: line 33: compare-heroku=!sh: command not found
Styleguide. Welcome!
PROGRESS:0
PROGRESS:50
(B[m/Users/victoryang/.extra: line 32: heroku-prod-deployed-commit=!sh: command not found
/Users/victoryang/.extra: line 33: compare-heroku=!sh: command not found

Checking dependencies...

/Users/victoryang/.rvm/scripts/extras/bash_zsh_support/chpwd/function.sh: line 5: cd: ../../../styleguide/structure/_node-files: No such file or directory
npm ERR! install Couldn't read dependencies
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/victoryang/.nvm/versions/node/v0.12.7/bin/node" "/Users/victoryang/.nvm/versions/node/v0.12.7/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path /private/var/folders/zw/h90f1y7n45v8l90_d68dw4140000gn/T/AppTranslocation/82184896-51AC-48E6-B1B5-E59AF470F27A/d/Start.app/Contents/Resources/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2

npm ERR! package.json ENOENT, open '/private/var/folders/zw/h90f1y7n45v8l90_d68dw4140000gn/T/AppTranslocation/82184896-51AC-48E6-B1B5-E59AF470F27A/d/Start.app/Contents/Resources/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/victoryang/.nvm/versions/node/v0.12.7/bin/node" "/Users/victoryang/.nvm/versions/node/v0.12.7/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path npm-debug.log.755c92c3807a864e8895130ac3de4537
npm ERR! code EROFS
npm ERR! errno -30

npm ERR! rofs EROFS, open 'npm-debug.log.755c92c3807a864e8895130ac3de4537'
npm ERR! rofs This is most likely not a problem with npm itself
npm ERR! rofs and is related to the file system being read-only.
npm ERR! rofs 
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/zw/h90f1y7n45v8l90_d68dw4140000gn/T/AppTranslocation/82184896-51AC-48E6-B1B5-E59AF470F27A/d/Start.app/Contents/Resources/npm-debug.log
PROGRESS:80
touch: .install.lock: Read-only file system
/Users/victoryang/.rvm/scripts/extras/bash_zsh_support/chpwd/function.sh: line 5: cd: styleguide/structure/_node-files: No such file or directory

Let's start this thing...
module.js:338
    throw err;
          ^
Error: Cannot find module '/private/var/folders/zw/h90f1y7n45v8l90_d68dw4140000gn/T/AppTranslocation/82184896-51AC-48E6-B1B5-E59AF470F27A/d/watch.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
PROGRESS:100
```

**Comment by Aaronkala** [comment]
@kylanhurt and @victorwhy I fixed that problem by removing the commandExists check in `styleguide/structure/_node-files/watch.js`

```javascript
// commandExists('harp', function(err, commandExists) {
//     if(!commandExists) {
//         console.log('Harp is not installed, please run npm install harp -g');
//         process.exit(1);
//     }
// });
```
Just make sure you have harp installed!

**Comment by fallenturtle** [comment]
I'm having the same issues. Tried both the hotfix version and Araonkala's idea and neither worked. I even installed Harp with no luck.

**Comment by interactiveRob** [comment]
@fallenturtle I got the same error, but had luck with the manual install process: 
http://hugeinc.github.io/styleguide/start.html#manual-install
